# Site settings
course_name: ResidenciaTICBrisa
course_description: "ResidenciaTICBrisa teste brisas."
course_semester: "adac"
pre_requisites: Basics of Multivariate Calculus and Linear Algebra.


baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://residenciaticbrisa.github.io" # the base hostname & protocol for your site

schoolname: "uNb"

address: |
    UnB | Universidade de Brasília
    FGA | Faculdade do gama
    LAPPIS | Laboratório Aplicado de Produção Pesquisa e Inovação em Software


emails: |
    caguiar@unb.br
   
github_username: lappis-unb
instagram_username: lappisunb
facebook_username: lappisunb5
# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%d/%m/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    post:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "post"
    values:
      layout: "post"
